//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjLibrarySystem
{
    public partial class MemberDashboard
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.ScriptManager ScriptManager1;

        protected global::System.Web.UI.WebControls.Label lblStudentName;

        protected global::System.Web.UI.WebControls.Label studentNotificationBadge;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl noStudentNotifications;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl studentNotificationList;

        protected global::System.Web.UI.WebControls.Label lblAvailableBooks;

        protected global::System.Web.UI.WebControls.Label lblBorrowedBooks;

        protected global::System.Web.UI.WebControls.Label lblOverdueBooks;

        protected global::System.Web.UI.WebControls.Label lblTotalBorrowed;

        protected global::System.Web.UI.WebControls.GridView gvRecommendations;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl noRecommendations;

        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;

        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;

        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl passwordError;

        protected global::System.Web.UI.WebControls.Label lblPasswordError;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl passwordSuccess;

        protected global::System.Web.UI.WebControls.Label lblPasswordSuccess;

        protected global::System.Web.UI.WebControls.Button btnChangePassword;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl notificationsList;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl noNotificationsModal;
    }
}
